import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-app.js';
import { getAuth, signInAnonymously, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-auth.js';
import { getDatabase, ref, set, onValue, onDisconnect, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-database.js';

const firebaseApp = initializeApp({ apiKey:'AIzaSyBQfbSNxn3MMvau0Ge6kIkIAbBsbO4xArk', authDomain:'neon-nomads-live.firebaseapp.com', databaseURL:'https://neon-nomads-live-default-rtdb.firebaseio.com', projectId:'neon-nomads-live', storageBucket:'neon-nomads-live.firebasestorage.app', messagingSenderId:'258338447421', appId:'1:258338447421:web:2dbf26b327476c0a77ca54' });
const auth = getAuth(firebaseApp), db = getDatabase(firebaseApp);
const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d'), mini = document.querySelector('#minimap').getContext('2d');
const el = id => document.getElementById(id), colors=['#ff5ebc','#6d78ff','#55e5d0','#ffbb60','#be72ff','#69b6ff','#fb6e6e'];
const track=(event,details={})=>window.gtag?.('event',event,details);
const ARENA={left:-6000,right:6000,top:-4200,bottom:4200};
let W,H,dpr, running=false, spectating=false, paused=false, pauseStarted=0, mass=12, foods=[], powerups=[], auraDrops=[], bots=[], player, mouse={x:0,y:0}, keys={}, t=0, last=0, lastInput=0, playerId=null, livePlayers={}, lastSync=0, scoreSync=0, scoreDirty=false, combo=0, comboTimer=0, power=null, powerUntil=0, eventClock=0, missionCount=0, voteChoice=null, blackoutUntil=0, activeAura=localStorage.neonNomadsAura||'', activeHead=localStorage.neonNomadsHead||'CLASSIC', bestCombo=0, runStarted=0;
const PRESENCE_TTL=15000, IDLE_TIMEOUT=60000, PAUSE_KICK_TIMEOUT=180000;
let headImage=null;const savedHeadPhoto=localStorage.neonNomadsPhoto||'';if(savedHeadPhoto){headImage=new Image();headImage.src=savedHeadPhoto}
let displayName = localStorage.neonNomadsName || (localStorage.neonNomadsName = `NOMAD-${Math.random().toString(36).slice(2,6).toUpperCase()}`);
const roomParam=new URLSearchParams(location.search).get('room')||'', currentRoom=roomParam.replace(/[^A-Z0-9-]/gi,'').toUpperCase().slice(0,16)||'PUBLIC';
const dailyKey=`neonNomadsDaily-${new Date().toISOString().slice(0,10)}`, dailyContracts=[['PRISM HUNT','Collect 30 energy prisms',30],['FLOW STATE','Collect 24 energy prisms',24],['GLOW RUN','Collect 36 energy prisms',36]], dailyContract=dailyContracts[new Date().getDate()%dailyContracts.length];
const auraDefs=[['STAR DUST','#f5ceff'],['GLITCH FIRE','#ff7bbb'],['MIDNIGHT ICE','#77dfff']];
const landmarks=[{x:0,y:0,name:'SPARK CORE',c:'#ff5ebc'},{x:950,y:-520,name:'AURORA GATE',c:'#59ebd7'},{x:-1050,y:610,name:'VIOLET VAULT',c:'#a975ff'},{x:1320,y:720,name:'GOLDEN DRIFT',c:'#ffbd5b'}], sectorNames=['EMBER RUN','VIOLET VAULT','AURORA GATE','GOLDEN DRIFT','ECHO FIELD','SPARK CORE','NOVA REACH','MIDNIGHT LOOP'];
const skyProps=[{type:'satellite',x:-720,y:-330,scale:1.05,tilt:-.3},{type:'ufo',x:610,y:360,scale:.9,tilt:.18},{type:'satellite',x:1280,y:-770,scale:.72,tilt:.48},{type:'ufo',x:-1420,y:760,scale:.68,tilt:-.14},{type:'satellite',x:280,y:-700,scale:.78,tilt:.2},{type:'ufo',x:-360,y:640,scale:.76,tilt:-.4},{type:'satellite',x:1500,y:180,scale:.9,tilt:-.12},{type:'ufo',x:-1120,y:-820,scale:.74,tilt:.32},{type:'satellite',x:930,y:940,scale:.68,tilt:.52},{type:'ufo',x:160,y:-1080,scale:.7,tilt:.08},{type:'satellite',x:-1680,y:-90,scale:.76,tilt:-.55},{type:'ufo',x:1680,y:-420,scale:.7,tilt:.26}];
const planets=[{x:860,y:-260,r:34,c:'#c37bff',ring:'#7ff1e2',phase:.3},{x:-1280,y:420,r:29,c:'#ff7fbd',ring:'#ffd277',phase:2.1},{x:360,y:1050,r:32,c:'#6e98ff',ring:'#d8c8ff',phase:4.4}];
missionCount=Number(localStorage.getItem(dailyKey)||0);
const botNames=['MIRAGE BOT','KITE BOT','EMBER BOT','GLOW BOT'];
function publishPresence(){ if(!playerId || !player) return; set(ref(db,`players/${playerId}`), {name:displayName,mass:Math.round(mass),color:player.color,x:Math.round(player.x),y:Math.round(player.y),room:currentRoom,vote:voteChoice||'',updatedAt:serverTimestamp(),active:running}); }
function isLivePlayer(p){return Boolean(p?.active)&&(!p.updatedAt||Date.now()-Number(p.updatedAt)<PRESENCE_TTL)}
function markOffline(){if(!playerId||!player)return;set(ref(db,`players/${playerId}`),{name:displayName,mass:Math.round(mass),color:player.color,x:Math.round(player.x),y:Math.round(player.y),room:currentRoom,vote:'',updatedAt:serverTimestamp(),active:false})}
onAuthStateChanged(auth,user=>{ if(!user) return; playerId=user.uid; const mine=ref(db,`players/${user.uid}`); onDisconnect(mine).remove().catch(()=>{}); if(player) publishPresence(); });
signInAnonymously(auth).catch(err=>console.warn('Guest sign-in unavailable',err));
onValue(ref(db,'players'),snapshot=>{livePlayers=snapshot.val()||{}; renderLeaderboard();renderVotes();const inRoom=Object.values(livePlayers).filter(p=>isLivePlayer(p)&&(p.room||'PUBLIC')===currentRoom).length;el('roomCount').textContent=inRoom;});
function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize); resize();
function rand(a,b){return a+Math.random()*(b-a)} function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function makeSnake(x,y,c,ai=false){let s={x,y,angle:rand(0,6.28),color:c,parts:[],len:ai?rand(24,43):14,speed:ai?rand(.7,1.25):1.7,ai,turn:0,dead:false};for(let i=0;i<s.len;i++)s.parts.push({x:x-i*5,y});return s}
function seed(){foods=[];powerups=[];auraDrops=[];bots=[];player=makeSnake(0,0,'#ff5ebc');for(let i=0;i<340;i++)foods.push({x:rand(-1700,1700),y:rand(-1200,1200),c:colors[i%colors.length],r:rand(2,4),cluster:i%19===0});for(let i=0;i<5;i++)spawnPowerup();spawnPowerup(-155,140,'LUMINOVA');spawnAura();for(let i=0;i<4;i++)bots.push(makeSnake(rand(-1400,1400),rand(-1000,1000),colors[(i+1)%colors.length],true));renderLeaderboard();}
function spawnSkyProp(){skyProps.push({type:Math.random()<.56?'satellite':'ufo',x:rand(-1700,1700),y:rand(-1150,1150),scale:rand(.68,1.06),tilt:rand(-.6,.6)})}
function spawnPlanet(){planets.push({x:rand(-1600,1600),y:rand(-1100,1100),r:rand(28,37),c:colors[Math.floor(Math.random()*colors.length)],ring:'#8df4e5',phase:rand(0,6.28)})}
function spawnPowerup(x=rand(-1550,1550),y=rand(-1050,1050),forcedKind=''){const kinds=[['MAGNET','#59ebd7'],['SHIELD','#8f7aff'],['SURGE','#ffbd5b'],['LUMINOVA','#ff4fd8']];const [kind,c]=forcedKind?kinds.find(item=>item[0]===forcedKind):kinds[Math.floor(Math.random()*kinds.length)];powerups.push({x,y,kind,c,phase:rand(0,6.28)});}
function spawnAura(){const [name,c]=auraDefs[Math.floor(Math.random()*auraDefs.length)];auraDrops.push({x:rand(-1500,1500),y:rand(-1050,1050),name,c,phase:rand(0,6.28)});}
function updateDailyUI(){const done=Math.min(missionCount,dailyContract[2]);el('missionTitle').textContent=dailyContract[0];el('missionText').textContent=done>=dailyContract[2]?'Contract complete · return tomorrow':`${done} / ${dailyContract[2]} energy prisms`;el('missionBar').style.width=Math.min(100,done/dailyContract[2]*100)+'%'}
function updateRunUI(){const progress=Math.min(100,mass/250*100);el('goalBar').style.width=progress+'%';el('goalText').textContent=mass>=250?'NOVA ACHIEVED':`${mass} / 250 MASS`;const active=el('activePower');if(power){const seconds=Math.max(1,Math.ceil((powerUntil-t)/60));const effects={MAGNET:'PULLING NEARBY ENERGY',SHIELD:'ONE CRASH BLOCKED',SURGE:'2× ENERGY GAINS',LUMINOVA:'RAINBOW TRAIL ACTIVE'};active.textContent=`${power} · ${seconds}S · ${effects[power]}`;active.classList.add('on')}else{active.textContent='NO POWER ACTIVE';active.classList.remove('on')}}
function pauseGame(){if(!running)return;paused=true;pauseStarted=performance.now();running=false;keys={};publishPresence();el('pauseCard').classList.remove('hidden');setTimeout(()=>{if(paused&&performance.now()-pauseStarted>=PAUSE_KICK_TIMEOUT){paused=false;markOffline();el('pauseCard').classList.add('hidden');el('startCard').classList.remove('hidden');toast('RUN ENDED · IDLE TOO LONG')}},PAUSE_KICK_TIMEOUT)}
function resumeGame(){if(!paused)return;paused=false;pauseStarted=0;running=true;lastInput=performance.now();last=lastInput;el('pauseCard').classList.add('hidden');publishPresence();requestAnimationFrame(loop)}
function recordInput(){if(paused){resumeGame();return}lastInput=performance.now()}
function reset(){spectating=false;paused=false;mass=12;combo=0;bestCombo=0;comboTimer=0;scoreSync=0;scoreDirty=false;power=null;powerUntil=0;eventClock=0;runStarted=performance.now();lastInput=runStarted;seed(); el('mass').textContent=mass;el('youScore').textContent=mass;el('massBar').style.width='5%';el('auraLabel').textContent=`AURA: ${activeAura||'NONE'}`;updateDailyUI();updateRunUI();el('deathCard').classList.add('hidden');el('pauseCard').classList.add('hidden');running=true;publishPresence();track('game_start',{room_type:currentRoom==='PUBLIC'?'public':'private'});last=performance.now();requestAnimationFrame(loop)}
function drawGrid(){const c=camera(),zone=Math.floor((Math.abs(c.x/620)+Math.abs(c.y/520)))%3,tones=['#080a1d','#091025','#100a24'];const bg=ctx.createRadialGradient(W*.5,H*.5,20,W*.5,H*.5,Math.max(W,H)*.7);bg.addColorStop(0,tones[zone]);bg.addColorStop(1,'#040510');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);drawArenaAtmosphere(c);let ox=(-c.x*.06)%52,oy=(-c.y*.06)%52;ctx.strokeStyle='rgba(125,135,220,.08)';ctx.lineWidth=1;for(let x=ox;x<W;x+=52){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const l of landmarks){const p=pos(l);if(p.x<-100||p.x>W+100||p.y<-100||p.y>H+100)continue;const glow=ctx.createRadialGradient(p.x,p.y,3,p.x,p.y,75);glow.addColorStop(0,l.c+'55');glow.addColorStop(1,l.c+'00');ctx.fillStyle=glow;ctx.fillRect(p.x-75,p.y-75,150,150);ctx.strokeStyle=l.c+'aa';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,18+Math.sin(t*.08+l.x)*3,0,7);ctx.stroke();ctx.fillStyle=l.c;ctx.font="9px 'DM Mono'";ctx.textAlign='center';ctx.fillText(l.name,p.x,p.y-30)}const origin=pos({x:0,y:0});ctx.strokeStyle='rgba(135,77,236,.2)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(origin.x,origin.y,Math.min(W,H)*.55,0,7);ctx.stroke()}
function drawArenaAtmosphere(c){ctx.save();ctx.globalCompositeOperation='screen';const blooms=[[-1250,-780,'#5f4de833'],[930,-460,'#10d8c52b'],[380,870,'#ff5ebc24']];for(const [x,y,color] of blooms){const p=pos({x:x+Math.sin(t*.012+y)*55,y:y+Math.cos(t*.01+x)*36}),g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,Math.max(W,H)*.42);g.addColorStop(0,color);g.addColorStop(1,'#00000000');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}for(let i=0;i<54;i++){const x=((i*617)%3600)-1800-c.x*.045,y=((i*353)%2600)-1300-c.y*.045,px=W/2+x,py=H/2+y;if(px<-4||px>W+4||py<-4||py>H+4)continue;const pulse=.25+Math.sin(t*.035+i*2.7)*.16;ctx.fillStyle=i%5===0?`rgba(113,242,224,${pulse})`:`rgba(197,172,255,${pulse*.7})`;ctx.beginPath();ctx.arc(px,py,i%9===0?1.6:.7,0,7);ctx.fill()}ctx.restore();drawSkyProps();drawPlanets()}
function drawSkyProps(){for(const prop of skyProps){const p=pos(prop);if(p.x<-100||p.x>W+100||p.y<-100||p.y>H+100)continue;const pulse=1+Math.sin(t*.045+prop.x)*.05;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(prop.tilt+Math.sin(t*.009+prop.y)*.04);ctx.scale(prop.scale*pulse,prop.scale*pulse);ctx.globalAlpha=.88;ctx.shadowBlur=22;ctx.shadowColor=prop.type==='ufo'?'#a975ff':'#59ebd7';if(prop.type==='satellite'){ctx.strokeStyle='#9beee7';ctx.lineWidth=1.4;ctx.fillStyle='#29345d';ctx.fillRect(-7,-4,14,8);ctx.strokeRect(-7,-4,14,8);ctx.fillStyle='#245a78';ctx.fillRect(-24,-7,13,14);ctx.fillRect(11,-7,13,14);ctx.strokeStyle='#70dfd0';ctx.strokeRect(-24,-7,13,14);ctx.strokeRect(11,-7,13,14);ctx.beginPath();ctx.moveTo(-11,0);ctx.lineTo(-7,0);ctx.moveTo(7,0);ctx.lineTo(11,0);ctx.moveTo(0,4);ctx.lineTo(6,12);ctx.stroke();ctx.fillStyle='#ffb8df';ctx.beginPath();ctx.arc(6,12,2,0,7);ctx.fill();ctx.font="8px 'DM Mono'";ctx.fillText('+18',0,47)}else{const beam=ctx.createRadialGradient(0,5,0,0,5,35);beam.addColorStop(0,'rgba(151,112,255,.25)');beam.addColorStop(1,'rgba(151,112,255,0)');ctx.fillStyle=beam;ctx.beginPath();ctx.ellipse(0,11,30,17,0,0,7);ctx.fill();ctx.fillStyle='#27355f';ctx.beginPath();ctx.ellipse(0,0,20,7,0,0,7);ctx.fill();ctx.strokeStyle='#b998ff';ctx.lineWidth=1.3;ctx.stroke();ctx.fillStyle='#9b75f1';ctx.beginPath();ctx.ellipse(0,-4,9,6,0,Math.PI,0);ctx.fill();ctx.fillStyle='#74f5e3';for(const x of [-10,0,10]){ctx.beginPath();ctx.arc(x,2,1.7,0,7);ctx.fill()}ctx.font="8px 'DM Mono'";ctx.fillText('POWER',0,47)}ctx.restore()}}
function drawPlanets(){for(const planet of planets){const p=pos(planet);if(p.x<-90||p.x>W+90||p.y<-90||p.y>H+90)continue;const pulse=1+Math.sin(t*.04+planet.phase)*.06;ctx.save();ctx.translate(p.x,p.y);ctx.scale(pulse,pulse);ctx.shadowBlur=28;ctx.shadowColor=planet.c;const glow=ctx.createRadialGradient(-planet.r*.25,-planet.r*.3,2,0,0,planet.r*1.7);glow.addColorStop(0,'#fff5ff');glow.addColorStop(.18,planet.c);glow.addColorStop(1,planet.c+'12');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,planet.r*1.25,0,7);ctx.fill();ctx.fillStyle=planet.c;ctx.beginPath();ctx.arc(0,0,planet.r,0,7);ctx.fill();ctx.globalAlpha=.28;ctx.fillStyle='#20164c';ctx.beginPath();ctx.arc(planet.r*.22,planet.r*.16,planet.r*.42,0,7);ctx.fill();ctx.globalAlpha=.9;ctx.rotate(-.28);ctx.strokeStyle=planet.ring;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,planet.r*1.55,planet.r*.46,0,0,7);ctx.stroke();ctx.rotate(.28);ctx.fillStyle='#f2eeff';ctx.font="9px 'DM Mono'";ctx.textAlign='center';ctx.fillText('+45 · SHIELD',0,planet.r+21);ctx.restore()}}
function camera(){return spectating?(bots.reduce((top,b)=>b.parts.length>top.parts.length?b:top,bots[0])||player):player}
function pos(p){const c=camera();return{x:W/2+(p.x-c.x),y:H/2+(p.y-c.y)}}
function drawArenaBoundary(){const topLeft=pos({x:ARENA.left,y:ARENA.top}),bottomRight=pos({x:ARENA.right,y:ARENA.bottom});if(bottomRight.x<0||topLeft.x>W||bottomRight.y<0||topLeft.y>H)return;ctx.save();ctx.strokeStyle='#59ebd7';ctx.globalAlpha=.75;ctx.shadowBlur=15;ctx.shadowColor='#59ebd7';ctx.setLineDash([10,8]);ctx.lineWidth=3;ctx.strokeRect(topLeft.x,topLeft.y,bottomRight.x-topLeft.x,bottomRight.y-topLeft.y);ctx.setLineDash([]);ctx.shadowBlur=0;ctx.font="10px 'DM Mono'";ctx.fillStyle='#9efff1';ctx.textAlign='center';if(topLeft.y>15&&topLeft.y<H-15)ctx.fillText('ARENA EDGE',W/2,topLeft.y-10);if(bottomRight.y>15&&bottomRight.y<H-15)ctx.fillText('ARENA EDGE',W/2,bottomRight.y+20);ctx.restore()}
function drawDanger(){if(!running)return;let nearest=Infinity;for(const b of bots)for(let i=5;i<b.parts.length;i++)nearest=Math.min(nearest,dist(player,b.parts[i]));if(nearest<170){const p=pos(player),strength=1-nearest/170;ctx.beginPath();ctx.strokeStyle=`rgba(255,94,188,${.14+strength*.4})`;ctx.lineWidth=2+strength*2;ctx.arc(p.x,p.y,24+Math.sin(t*.18)*5+strength*18,0,7);ctx.stroke()}}
function drawFood(){for(const f of foods){let p=pos(f);if(p.x<-18||p.x>W+18||p.y<-18||p.y>H+18)continue;if(f.cluster){for(let n=0;n<4;n++){const a=n*1.57+t*.015;ctx.beginPath();ctx.fillStyle=f.c+'99';ctx.arc(p.x+Math.cos(a)*8,p.y+Math.sin(a)*8,1.8,0,7);ctx.fill()}}ctx.beginPath();ctx.fillStyle=f.c+'33';ctx.arc(p.x,p.y,f.cluster?f.r*5:f.r*3.7,0,7);ctx.fill();ctx.beginPath();ctx.fillStyle=f.c;ctx.arc(p.x,p.y,f.cluster?f.r+1:f.r,0,7);ctx.fill()}}
function drawPowerups(){for(const u of powerups){const p=pos(u), pulse=1+Math.sin(t*.1+u.phase)*.16,rare=u.kind==='LUMINOVA',size=rare?1.55:1;if(p.x<-45||p.x>W+45||p.y<-45||p.y>H+45)continue;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(t*.015+u.phase);ctx.shadowBlur=rare?28:10;ctx.shadowColor=u.c;ctx.fillStyle=u.c+'2c';ctx.beginPath();ctx.arc(0,0,15*pulse*size,0,7);ctx.fill();ctx.strokeStyle=u.c;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-8*pulse*size);ctx.lineTo(8*pulse*size,0);ctx.lineTo(0,8*pulse*size);ctx.lineTo(-8*pulse*size,0);ctx.closePath();ctx.stroke();if(rare){ctx.rotate(-t*.03);ctx.beginPath();ctx.moveTo(0,-12*pulse*size);ctx.lineTo(0,12*pulse*size);ctx.moveTo(-12*pulse*size,0);ctx.lineTo(12*pulse*size,0);ctx.stroke();ctx.rotate(t*.015+u.phase);ctx.font="10px 'DM Mono'";ctx.textAlign='center';ctx.fillStyle='#ffb2ed';ctx.fillText('LUMINOVA',0,-31)}ctx.restore();}}
function drawAuras(){for(const a of auraDrops){const p=pos(a),pulse=1+Math.sin(t*.11+a.phase)*.22;if(p.x<-35||p.x>W+35||p.y<-35||p.y>H+35)continue;ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=a.c;ctx.shadowBlur=16;ctx.shadowColor=a.c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,12*pulse,0,7);ctx.stroke();ctx.beginPath();ctx.arc(0,0,5,0,7);ctx.stroke();ctx.restore();}}
function collectAuras(){for(let i=auraDrops.length-1;i>=0;i--)if(dist(player,auraDrops[i])<24){const a=auraDrops[i];auraDrops.splice(i,1);activeAura=a.name;localStorage.neonNomadsAura=activeAura;el('auraLabel').textContent=`AURA: ${activeAura}`;toast(`${activeAura} UNLOCKED`);setTimeout(spawnAura,18000)}}
function collectSkyProps(){for(let i=skyProps.length-1;i>=0;i--)if(dist(player,skyProps[i])<38){const prop=skyProps[i];skyProps.splice(i,1);if(prop.type==='satellite'){mass+=18;scoreDirty=true;el('mass').textContent=mass;el('youScore').textContent=mass;el('massBar').style.width=Math.min(100,mass/2.5)+'%';toast('SATELLITE CACHE +18 MASS')}else{power=Math.random()<.5?'SURGE':'LUMINOVA';powerUntil=t+840;toast(`UFO RELAY · ${power} · 14 SEC`)}setTimeout(spawnSkyProp,15000)}}
function collectPlanets(){for(let i=planets.length-1;i>=0;i--)if(dist(player,planets[i])<52){planets.splice(i,1);mass+=45;scoreDirty=true;power='SHIELD';powerUntil=t+1200;el('mass').textContent=mass;el('youScore').textContent=mass;el('massBar').style.width=Math.min(100,mass/2.5)+'%';toast('PLANET CORE +45 MASS · SHIELD 20 SEC');setTimeout(spawnPlanet,45000)}}
function drawSnake(s){let pts=s.parts.map(pos),grow=s===player?Math.min(5,mass/55):0,luminova=s===player&&power==='LUMINOVA';ctx.lineCap='round';ctx.lineJoin='round';for(let i=pts.length-1;i>0;i--){ctx.beginPath();ctx.strokeStyle=luminova?`hsl(${(t*3+i*13)%360} 100% 68%)`:s.color+(i<4?'ee':'88');ctx.lineWidth=Math.max(3,9+grow-i*.11);if(luminova){ctx.shadowBlur=13;ctx.shadowColor=ctx.strokeStyle}ctx.moveTo(pts[i].x,pts[i].y);ctx.lineTo(pts[i-1].x,pts[i-1].y);ctx.stroke();ctx.shadowBlur=0}let h=pts[0],head=s===player?activeHead:'CLASSIC',size=9+grow*.32;if(s===player&&mass>=100){ctx.beginPath();ctx.fillStyle=s.color+'33';ctx.arc(h.x,h.y,17+grow,0,7);ctx.fill()}ctx.fillStyle=luminova?'#fff2ff':s.color;if(head==='PHOTO'&&headImage&&headImage.complete){ctx.save();ctx.beginPath();ctx.arc(h.x,h.y,size+1,0,7);ctx.clip();ctx.drawImage(headImage,h.x-size-1,h.y-size-1,(size+1)*2,(size+1)*2);ctx.restore();ctx.strokeStyle='#fff4';ctx.lineWidth=1;ctx.beginPath();ctx.arc(h.x,h.y,size+1,0,7);ctx.stroke()}else if(head==='PIXEL')ctx.fillRect(h.x-size,h.y-size,size*2,size*2);else{ctx.beginPath();ctx.arc(h.x,h.y,head==='CYCLOPS'?size+1:size,0,7);ctx.fill()}if(head!=='PHOTO'){ctx.fillStyle='#15162b';if(head==='CYCLOPS'){ctx.beginPath();ctx.arc(h.x+Math.cos(s.angle)*3.6,h.y+Math.sin(s.angle)*3.6,2.9,0,7);ctx.fill();ctx.fillStyle='#f5f7ff';ctx.beginPath();ctx.arc(h.x+Math.cos(s.angle)*4.3,h.y+Math.sin(s.angle)*4.3,1.1,0,7);ctx.fill()}else{ctx.beginPath();ctx.arc(h.x+Math.cos(s.angle-.5)*3.7,h.y+Math.sin(s.angle-.5)*3.7,1.5,0,7);ctx.arc(h.x+Math.cos(s.angle+.5)*3.7,h.y+Math.sin(s.angle+.5)*3.7,1.5,0,7);ctx.fill()}}if(head==='CROWN'){ctx.fillStyle='#ffdc65';ctx.beginPath();ctx.moveTo(h.x-8,h.y-6);ctx.lineTo(h.x-4,h.y-14);ctx.lineTo(h.x,h.y-8);ctx.lineTo(h.x+4,h.y-14);ctx.lineTo(h.x+8,h.y-6);ctx.closePath();ctx.fill()}}
function move(s,dt){let sp=s.speed*dt*(s===player&&keys.Space?1.8:1);s.x+=Math.cos(s.angle)*sp;s.y+=Math.sin(s.angle)*sp;const hitX=s.x<ARENA.left||s.x>ARENA.right,hitY=s.y<ARENA.top||s.y>ARENA.bottom;s.x=Math.max(ARENA.left,Math.min(ARENA.right,s.x));s.y=Math.max(ARENA.top,Math.min(ARENA.bottom,s.y));if(s.ai){if(hitX)s.angle=Math.PI-s.angle;if(hitY)s.angle=-s.angle}s.parts.unshift({x:s.x,y:s.y});const targetLength=s===player?Math.min(96,14+Math.floor(mass/2)):s.len;while(s.parts.length>targetLength)s.parts.pop();if(s===player&&keys.Space&&mass>12&&Math.random()<.03){mass--;scoreDirty=true;foods.push({x:s.x-rand(-10,10),y:s.y-rand(-10,10),c:s.color,r:3})}}
function spectateUpdate(dt){for(const b of bots){b.turn+=dt;if(b.turn>70){b.turn=0;b.angle+=rand(-1.1,1.1)}move(b,dt)}}
function update(dt){if(performance.now()-lastInput>IDLE_TIMEOUT){pauseGame();return}scoreSync+=dt;let target=Math.atan2(mouse.y-H/2,mouse.x-W/2);if(keys.KeyW)target=-Math.PI/2;if(keys.KeyS)target=Math.PI/2;if(keys.KeyA)target=Math.PI;if(keys.KeyD)target=0;let d=Math.atan2(Math.sin(target-player.angle),Math.cos(target-player.angle));player.angle+=d*Math.min(1,.12*dt);move(player,dt);if(power&&t>powerUntil){toast(`${power} EXPIRED`);power=null}if(power==='MAGNET')for(const f of foods){const dx=player.x-f.x,dy=player.y-f.y,ds=Math.hypot(dx,dy);if(ds<180&&ds>8){f.x+=dx/ds*dt*2.4;f.y+=dy/ds*dt*2.4}}for(const b of bots){b.turn+=dt;if(b.turn>80){b.turn=0;b.angle+=rand(-1.2,1.2)}let near=foods.reduce((a,f)=>dist(b,f)<dist(b,a)?f:a,foods[0]);if(near&&dist(b,near)<180)b.angle+=Math.atan2(Math.sin(Math.atan2(near.y-b.y,near.x-b.x)-b.angle),Math.cos(Math.atan2(near.y-b.y,near.x-b.x)-b.angle))*.025;move(b,dt)}comboTimer-=dt;for(let i=foods.length-1;i>=0;i--)if(dist(player,foods[i])<13){foods.splice(i,1);if(comboTimer<=0)combo=0;combo++;comboTimer=55;missionCount++;localStorage.setItem(dailyKey,missionCount);mass+=power==='SURGE'?4:2;scoreDirty=true;el('mass').textContent=mass;el('youScore').textContent=mass;el('massBar').style.width=Math.min(100,mass/2.5)+'%';updateDailyUI();if(combo>3&&combo%4===0)toast(`${combo}x FLOW COMBO`);if(missionCount===dailyContract[2]){mass+=8;scoreDirty=true;el('mass').textContent=mass;el('youScore').textContent=mass;toast('DAILY CONTRACT COMPLETE +8')}renderLeaderboard()}collectSkyProps();collectPlanets();if(scoreDirty&&scoreSync>12){scoreSync=0;scoreDirty=false;publishPresence()}for(let i=powerups.length-1;i>=0;i--)if(dist(player,powerups[i])<22){const u=powerups[i];powerups.splice(i,1);power=u.kind;powerUntil=t+480;toast(`${u.kind} ONLINE · 8 SEC`);setTimeout(spawnPowerup,5000)}eventClock+=dt;if(eventClock>1800){eventClock=0;resolveVote()}lastSync+=dt;if(lastSync>55){lastSync=0;publishPresence()}for(const b of bots)for(let i=6;i<b.parts.length;i++)if(dist(player,b.parts[i])<8){if(power==='SHIELD'){power=null;toast('SHIELD SHATTERED');return}return die()}}
function showEvent(title,text){el('eventTitle').textContent=title;el('eventText').textContent=text;const banner=el('eventBanner');banner.classList.remove('hidden');banner.classList.add('show');setTimeout(()=>{banner.classList.remove('show');setTimeout(()=>banner.classList.add('hidden'),300)},3200)}
function inCurrentRoom(p){return (p.room||'PUBLIC')===currentRoom}
function renderVotes(){const counts={COMET:0,BLACKOUT:0,MAGNET:0};for(const p of Object.values(livePlayers))if(p.active&&inCurrentRoom(p)&&counts[p.vote]!==undefined)counts[p.vote]++;el('voteComet').textContent=counts.COMET;el('voteBlackout').textContent=counts.BLACKOUT;el('voteMagnet').textContent=counts.MAGNET;document.querySelectorAll('[data-vote]').forEach(b=>b.classList.toggle('selected',b.dataset.vote===voteChoice))}
function resolveVote(){const counts={COMET:0,BLACKOUT:0,MAGNET:0};for(const p of Object.values(livePlayers))if(p.active&&inCurrentRoom(p)&&counts[p.vote]!==undefined)counts[p.vote]++;const winner=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];voteChoice=null;publishPresence();renderVotes();if(winner==='COMET'){for(let i=0;i<28;i++)foods.push({x:player.x+rand(-420,420),y:player.y+rand(-300,300),c:'#ffbd5b',r:rand(3,5)});showEvent('COMET SHOWER','Gold energy has entered your sector')}else if(winner==='MAGNET'){power='MAGNET';powerUntil=t+420;showEvent('MAGNET FIELD','All nearby energy is pulling toward you')}else{blackoutUntil=t+360;showEvent('BLACKOUT','Grid lights out · follow the glow')}}
function evolution(){return mass>=250?'NOVA':mass>=100?'PLASMA':mass>=40?'ARC':'SPARK'}
function toast(message='+ 1 ENERGY'){let x=el('toast');x.textContent=message;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),700)}
function drawMini(){const c=camera();mini.clearRect(0,0,140,140);mini.fillStyle='#0a0d24';mini.fillRect(0,0,140,140);mini.strokeStyle='#303a72';mini.setLineDash([3,3]);mini.strokeRect(5,5,130,130);mini.setLineDash([]);for(const l of landmarks){const x=70+(l.x-c.x)/35,y=70+(l.y-c.y)/35;if(x>4&&x<136&&y>4&&y<136){mini.fillStyle=l.c;mini.beginPath();mini.arc(x,y,3,0,7);mini.fill()}}mini.fillStyle='#7d88c6';for(const b of bots){mini.beginPath();mini.arc(70+(b.x-c.x)/35,70+(b.y-c.y)/35,2,0,7);mini.fill()}if(!spectating){mini.fillStyle='#ff5ebc';mini.beginPath();mini.arc(70,70,4,0,7);mini.fill()}mini.strokeStyle='#59ebd766';mini.beginPath();mini.arc(70,70,21,0,7);mini.stroke();const sx=Math.floor((c.x+1800)/450),sy=Math.floor((c.y+1300)/390),sector=sectorNames[Math.abs(sx+sy*3)%sectorNames.length];el('sectorLabel').textContent=sector.toUpperCase();el('coordsLabel').textContent=`GRID ${String(sx).padStart(2,'0')} · ${String(sy).padStart(2,'0')}`}
function loop(now){if(!running&&!spectating)return;let dt=Math.min(2.3,(now-last)/16.67);last=now;t+=dt;if(running){update(dt);collectAuras();updateRunUI()}else spectateUpdate(dt);drawGrid();drawArenaBoundary();drawFood();drawPowerups();drawAuras();bots.forEach(drawSnake);drawDanger();if(running&&power){const p=pos(player);ctx.beginPath();ctx.strokeStyle=power==='SHIELD'?'#8f7aff':power==='MAGNET'?'#59ebd7':power==='LUMINOVA'?'#ff4fd8':'#ffbd5b';ctx.lineWidth=2;ctx.globalAlpha=.65;ctx.arc(p.x,p.y,18+Math.sin(t*.12)*3,0,7);ctx.stroke();ctx.globalAlpha=1}if(running)drawSnake(player);if(t<blackoutUntil){ctx.fillStyle='rgba(0,0,8,.56)';ctx.fillRect(0,0,W,H)}drawMini();if(spectating)el('rank').textContent='WATCH';el('trailStage').textContent=spectating?'TRAIL: WATCHING':`TRAIL: ${power==='LUMINOVA'?'LUMINOVA':evolution()}`;el('voteTimer').textContent=`NEXT: ${Math.max(1,Math.ceil((1800-eventClock)/60))}s`;requestAnimationFrame(loop)}
function die(){running=false;publishPresence();const seconds=Math.max(1,Math.round((performance.now()-runStarted)/1000));track('game_end',{mass,seconds,room_type:currentRoom==='PUBLIC'?'public':'private'});el('deathStats').textContent=`You gathered ${mass} mass, reached ${el('rank').textContent}, and survived ${seconds}s.`;el('recapChip').textContent=`ARENA RECAP · ${mass} MASS · ${seconds} SEC`;el('shareBtn').dataset.shareText=`I hit ${mass} mass in ${seconds}s on SnakeSpark. Can you beat my run?`;el('spectateBtn').onclick=()=>{spectating=true;el('deathCard').classList.add('hidden');last=performance.now();toast('SPECTATING THE ARENA');requestAnimationFrame(loop)};el('deathCard').classList.remove('hidden')}
canvas.addEventListener('mousemove',e=>{mouse={x:e.clientX,y:e.clientY};recordInput()});addEventListener('keydown',e=>{keys[e.code]=true;recordInput()});addEventListener('keyup',e=>{keys[e.code]=false;recordInput()});addEventListener('snakespark-resume',resumeGame);addEventListener('pagehide',markOffline);canvas.addEventListener('touchmove',e=>{let q=e.touches[0];mouse={x:q.clientX,y:q.clientY};recordInput()},{passive:true});
function renderLeaderboard(){const people=Object.entries(livePlayers).filter(([,p])=>isLivePlayer(p)&&inCurrentRoom(p)).map(([id,p])=>({id,name:p.name||'NOMAD',mass:Number(p.mass)||0,color:p.color||'#59ebd7'}));const rows=people.sort((a,b)=>b.mass-a.mass);el('leaderList').innerHTML=rows.filter(r=>r.id!==playerId).slice(0,7).map(r=>`<li><span class="dot" style="background:${r.color}"></span><span>${r.name}</span><strong>${r.mass}</strong></li>`).join('')||'<li><span>Waiting for players…</span></li>';const mine=rows.findIndex(r=>r.id===playerId);el('rank').textContent=mine<0?'#—':'#'+(mine+1);}
function saveNickname(value){const clean=value.replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,20);if(!clean)return false;displayName=clean;localStorage.neonNomadsName=clean;el('nicknameBtn').textContent=clean;el('nicknameInput').value=clean;publishPresence();return true}el('nicknameBtn').textContent=displayName;el('nicknameInput').value=displayName;el('nicknameBtn').onclick=()=>{const value=prompt('Choose a nickname (up to 20 characters)',displayName);if(value!==null&&saveNickname(value))toast('NICKNAME UPDATED')};el('playBtn').onclick=()=>{if(!saveNickname(el('nicknameInput').value)){el('nicknameInput').focus();toast('ADD A CALLSIGN');return}el('startCard').classList.add('hidden');reset()};el('againBtn').onclick=reset;el('soundBtn').onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==='♬'?'×':'♬';el('arenaBtn').onclick=()=>{el('startCard').classList.add('hidden');reset();toast('NEW ARENA')};el('skinsBtn').onclick=()=>{const palette=['#ff5ebc','#59ebd7','#8f7aff','#ffbd5b','#ff7373','#76b7ff'];const next=palette[(palette.indexOf(player.color)+1)%palette.length];player.color=next;el('skinsBtn').style.cssText=`color:${next};border-color:${next};box-shadow:0 0 16px ${next}66`;publishPresence();toast('TRAIL UPDATED')};el('settingsBtn').onclick=()=>{document.body.classList.toggle('focus-mode');const enabled=document.body.classList.contains('focus-mode');el('settingsBtn').classList.toggle('active',enabled);toast(enabled?'FOCUS VIEW ON':'FOCUS VIEW OFF')};document.querySelectorAll('[data-vote]').forEach(button=>button.onclick=()=>{voteChoice=button.dataset.vote;publishPresence();renderVotes();toast(`${voteChoice} VOTE LOCKED`)});seed();updateDailyUI();renderVotes();drawGrid();drawFood();drawPowerups();bots.forEach(drawSnake);drawSnake(player);drawMini();
